package com.Jakko.enums;

public enum WaitingType {
    START, SET_FULL_NAME, SET_PHONE_NUMBER, PHOTO,
    CHOOSE_OPTION, CONFIRM, SET_TEXT,SEARCH_BUTTON,

    CHOOSE_FUNCTION, SET_PHOTO, OWN_VERSION,

    EXECUTED, IN_PROCESS,START_DATE,


    CHOOSE_DATE, CHOOSE_EXTRUDER, NOMENCLATURES,CHOOSE_NOMENCLATURES,EYES,CIRCLE,TIME,
    COUNT, REJECT_TIME,REJECT_REASON, SET_DATE, OPTION,DESCRIPTION,CHOOSE_UNIT, CHOOSE_PRIORITY

}
